### ISSUE TITLE
question about the config

### ISSUE THREAD

**Issue by stoeckley** [michaelnisi/backfire#1]
I'm curious about this line:

`-subj "/C=US/ST=CA/O=Swift/OU=example/CN=localhost"`

Does `localhost` get replaced by a remote server not on your local network, or is this always the setting?

And is `Swift` necessary here, or will this cert work with other languages you use on iOS?

**Comment by michaelnisi** [comment]
The subject here is exemplary: `Swift`can be anything; `localhost`is your host, the example runs a server at `localhost:8081`.
